### ISSUE TITLE
Pipeline or Strategy style?

### ISSUE THREAD

**Issue by eugene-eeo** [datalib/libextract#1]
Currently there are two methods of extraction that I have implemented, pipeline (function based) and strategy (inheritance based) style. I am not quite sure which style to use, any suggestions?
### Pipeline style

``` python
def custom_get_text(node):
    return node.xpath(SELECT_TEXT)

strategy = list(html.STRATEGY)
strategy[-1] = custom_get_text
```

**Pros:**
- Higher performance (in theory) as functions are easier to optimise
- No shared state, easy to debug compared to OO approach
- More elegant looking, more expressive (strategies can just be `[get_nodepairs, get_best, get_text]`)
- Code as data (pipelines are just lists)

**Cons:**
- May be slower due to use of many functions
- Not configurable (at the moment)
### Strategy style

``` python
class CustomFinder(HTMLFinder):
    text_nodes = 'custom_selector'
```

**Pros:**
- More configurable and easier to configure
- Most developers are more familiar
- Shared state can be used for optimisation

**Cons:**
- Hard to test and debug
- May be slower due to opaque objects

**cc @rodricios**

**Comment by rodricios** [comment]
For me the pipeline approach seems more attractive and faster to work with.

For that case though, we would have to specify and make obvious the order of the singular methods required for effective extraction ie., 

1. parse *ml document
2. get iterable of (nodes, length) pair
3. build histogram
4. get highest scoring element (possibly move up to step 3?)
5. get text

```
STRATEGY = (get_etree, get_pairs, histogram,
            highest_scoring, get_final_text)
```

@eugene-eeo: I'm a little confused by what you mean by "configurable". Referring to custom xpath selections?

**Comment by rodricios** [comment]
We could go the decorator route. 

Let's assume that we have our default pipeline method stack (html.STRATEGY)

Let's also assume that we reserved names for the 5 steps, say: 

1. get_etree
2. get_pairs
3. histogram
4. highest_scoring (or [argmax](https://github.com/libextract/libextract/issues/4))
5. get_final_text

Now what I'm proposing is basically a convention like so:

the user defines an extract method (or whatever they want to call it) that will return an html string or document.

```python
def extract(url):
    from requests import get

    return get('http://en.wikipedia.org/wiki/Classifier_(linguistics)').content
```

And they then stack decorators in a fashion that would, I believe, make the pipeline approach configurable. First, the default pipeline stack could be reconstructed with decorators:

```python

@get_final_text
@argmax
@histogram
@get_pairs
@get_etree
def extract(url):
    ...

print extract(url)
```

Arguably, the above looks unappealing, but that can be mitigated by combining two or more functions into one (like histogram & argmax for example). 

And now practically speaking, I see the following hypothetical usage:

Some one defines a custom get-text function and decorates the "extract" function:

```python
def get_final_text(func):
    def decorator(pair)
        node, _ = pair
        return func(node.xpath(SELECT_TEXT))
    return decorator
...
@get_final_text
def extract(url):
    from requests import get
    return get('http://en.wikipedia.org/wiki/Classifier_(linguistics)').content

print extract(url)
```

With the above or something similar to the above (on the side of "simpler"), I think we have
a pythonic(?) version of: 

```python
def custom_get_text(node):
    return node.xpath(SELECT_TEXT)

strategy = list(html.STRATEGY)
strategy[-1] = custom_get_text
```

Thoughts?

cc @eugene-eeo

**Comment by eugene-eeo** [comment]
@rodricios configurable in this case means that the approach, or strategy is more easily modified than the OO Strategy pattern. I think we should just create a Pipeline object with syntactic sugar to make constructing them more pleasing, instead of having stacked decorators:

```python
from livextract.pipeline import Pipeline

strategy = Pipeline(lambda x: get(x).content)\
                 .combine(html.STRATEGY)
```

But thats just one approach.

**Comment by eugene-eeo** [comment]
Also the histogram step was deliberately kept separate in order for other steps to be able to use the histogram for their own purposes (e.g. top 3, top 5, etc.).

**Comment by rodricios** [comment]
Wont hurt in trying out an implementation! Will the Pipeline object serve as a type of glorified list/tuple? I should note that the coretools.pipeline function is genius in my book :P

**Comment by eugene-eeo** [comment]
Yes, it's a glorified list! :sweat_smile:

**Comment by rodricios** [comment]
See my comment on your last commit. We should have an option like "international=False", for speedups on english sites, but unfortunately non-english will suffer exec.time-wise

**Comment by rodricios** [comment]
Checkout this [branch](https://github.com/libextract/libextract/tree/new_strategy). I added a new predefined strategy ``NODE_STRATEGY`` and changed ``STRATEGY`` TO ``TEXT_STRATEGY``.

I'm not sure if this is the direction we want to go though... making more and more strategies for common use cases (and corner cases). 

For the motivation of adding ``NODE_STRATEGY``: Someone on twitter mentioned they liked that eatiht could not only extract the raw text, but also extract the html node, which they can then send to other parts of their app.

**Comment by eugene-eeo** [comment]
Yes, that's the recommended way to use the pipeline, which is for the library to provide multiple small, composable functions similar to the Unix pipes. And yes, we should move the strategies to a separate file. I think we should only provide two strategies as those are what most people would use most of the time, anyways.

**Comment by rodricios** [comment]
Alright then! I'll make the appropriate changes and merge.

**Comment by Beluki** [comment]
Hi there! May I chime in to give an opinion?

I prefer the object-oriented approach in this particular case.

My rationale is that it makes it easier to add things such as pretty-printing or tracing steps in the middle of the computation. This helps debugging.

Another option that is somewhere in between both approaches and allows configuration is using closures. Made-up example as I don't know anything about libextract's internals:

```python
def score_higher_than(value):
    def custom(node):
         return node.score > value
    return custom

STRATEGY = ( score_higher_than(20), get_etree, get_pairs )
```

On performance:

When I wrote [MQLite](https://github.com/Beluki/MQLite), I heavily benchmarked all of those approaches: single functions, classes and closures.

In CPython I found functions and closures to be faster than classes (sometimes 2x faster depending on how many applications are needed). Using `__call__` to emulate functions was also slower than having a dedicated method in the class. In Pypy the difference was non-existant for all practical purposes.

I also found that as soon as the classes/functions do anything non-trivial, the performance difference becomes negligible. In my program, I create trees of matching classes and call methods from them thousands of times (as many as there are input records). The performance hit is basically 0 when compared to the work the methods actually do.

**Comment by eugene-eeo** [comment]
@Beluki thanks for dropping by, I really appreciate it! I also considered OO approach but pipelines tend to be more descriptive, if at the cost of the developer needing to know the exact steps. I am currently brainstorming about how to make these pipelines more friendlier to work with, do you have any ideas?

Also I am aware that functions are relatively expensive in Python. I just thought that PyPy would JIT-compile functions better than classes. Apparently not.

**Comment by Beluki** [comment]
> I just thought that PyPy would JIT-compile functions better than classes

My guess is that Pypy inlines both when it cans and thus there's no performance difference.

> Do you think partials or closures are better as configuration?

When compared to bare functions, yes, because they hold state, for example the result of compiling an input regular expression. They also make possible to create functions that act on functions such as combining transformations in particular ways.

Consider the following contrived example (it's a bit long, but I hope illustrative):

```python
import re

def PipeRegex(regex):   
    compiled_re = re.compile(regex)
    
    def custom(data):
        if compiled_re.match(data):
            return data
    return custom

def PipeSlice(start, end):
    def custom(data):
        return data[start:end]
    return custom
        
def When(function1, function2):
    def custom(node):
        if function1(node):
            return function2(node)
    return custom
    
    
test = When(PipeRegex("^Hello"), PipeSlice(5, None))
print(test("Hello World"))
```

Another example would be a Debug(function1, function2, ... functionN) that displays the data  before and after applying the functions transformation, optionally waiting for a keypress. Without closures or some kind of configuration facility I would have to put a single "print" function inside the pipeline every time I want the output.

**Comment by rodricios** [comment]
If I'm not mistake, @Beluki is saying that functions are less expensive that classes. But this may be a separate issue. 

I think @Beluki's closure suggestion resonates with the direction libextract is going. 

To @eugene-eeo's "partials or closures" question:

functool's partial was something I considered when attempting to converge the get_*_pairs functions. 

```python 
STRATEGY = (parse_html,
            partial(get_pairs, prep_func=COUNT_SUBNODES,
            node_counter_argmax,
            sort_best_pairs,
            filter_tags)
```

Idk if this is helpful or not but scrapy has a [pipelining](https://github.com/scrapy/scrapy/tree/master/scrapy/contrib/pipeline) mechanism, but it's arguably a different beast than what we're trying to tame. They handle dynamic processing of "item" (html) extraction in the middle of crawling jobs.

**Comment by rodricios** [comment]
Some how I missed the @Beluki's comment above mine. You're example was very illustrative. I'll try to implement something along the same grain. Thanks!

**Comment by rodricios** [comment]
The following is one possible way of addressing the Debug function @Beluki metioned. 

```python
import re
from functools import wraps

def PipeRegex(regex):   
    compiled_re = re.compile(regex)
    @wraps(PipeRegex)
    def custom(data):
        if compiled_re.match(data):
            return data
    return custom

def PipeSlice(start, end):
    @wraps(PipeSlice)
    def custom(data):
        return data[start:end]
    return custom

def Debug(*args):
    def custom(data):
        for func in args:
            data = func(data)
            if data:
                print("{0} running ... output: {1})".format(func.__name__, data))
                input("Press <Enter> to continue")
        return data
    return custom

test = Debug(PipeRegex("^Hello"), PipeSlice(5, None))
out = test("Hello World")
```

Now... the question is, how should the code be refactored? I'm thinking, there should be a "lower" level set of Pipe* functions that are to be decorated onto our current set of fuctions within the libextract.html submodule.

**Comment by Beluki** [comment]
> one possible way of addressing the Debug function

Yeah, that was the idea, nice implementation.

>  how should the code be refactored? there should be a "lower" level set of Pipe* functions that are to be decorated onto our current set of fuctions...

That's the hardest part in my opinion, deciding what should be added and why. I was fortunate in my project that the primitives were actually dictated by the pattern matching specification, so the design was clear.

For libextract, I think the best way to go about it is to write the functions as if combinations of them weren't available. I mean implementing `parse_html`, `get_pairs`, `node_counter_argmax`, `sort_best_pairs`, etc from the above post, but avoiding the esoteric stuff such as `when` and combinators, perhaps with some really useful exceptions, like `debug`.

My rationale for this is that the important thing is to make the pipeline easily extensible/configurable and documenting how users can extend it. Closures allow that. What extensions are needed will probably come up as people use libextract and implement their own transformations.

**Comment by sybrandy** [comment]
Just a quick drive-by comment: as much as possible, I would recommend going with the functional approach.  Like you said: it makes it very easy to test the methods since there is no shared state.  This is not to say you can't use other patterns as well.  I'm just saying that the more pure your functions are, the better off I believe you'll be.

**Comment by eugene-eeo** [comment]
@sybrandy I'm 100% with you on this, just a bit unsure of what others may think and what would be the more performant/pythonic version.

**Comment by rodricios** [comment]
@sybrandy, @Beluki thanks to you both for giving your thoughts! :)

I'm sure @eugene-eeo and I will have fun with this one. We'll hopefully be iterating over possible implementations, please stay tuned!

**Comment by sybrandy** [comment]
@eugene-eeo Unfortunately I can't say which is is more performant/pythonic since I don't use Python.  Good luck.

**Comment by msiemens** [comment]
> what would be the more performant/pythonic version.

I think it'd be the best to first take the most pythonic approach and then do some thorough profiling to maximize performance as needed. That being said, the functional approach looks really good to me as it's reflecting the series of steps needed to extract the article text in a very intuitive way.
