### ISSUE TITLE
Proposal for using A.I. terminology

### ISSUE THREAD

**Issue by rodricios** [datalib/libextract#21]
Tree traversal and optimization have long been tenets in A.I. and machine learning.

This library is, to some extent, a machine learning library. But more than that, we hope that it can be a useful library that's easy to pick up. 

That being said, I'd like to propose the use of the following terms: ``prune``, ``optimizers`` or ``maximizers``, and ``heuristics``

[Pruning is a technique in machine learning that reduces the size of decision trees by removing sections of the tree that provide little power to classify instances](http://en.wikipedia.org/wiki/Pruning_%28decision_trees%29)

[Optimization (alternatively, optimization or mathematical programming) is the selection of a best element (with regard to some criteria) from some set of available alternatives](http://en.wikipedia.org/wiki/Mathematical_optimization)

[A heuristic technique, sometimes called simply a heuristic, is any approach to problem solving, learning, or discovery that employs a practical methodology not guaranteed to be optimal or perfect, but sufficient for the immediate goals](http://en.wikipedia.org/wiki/Heuristic)

The ``get_*_pairs`` functions in article.py and tabular.py can both be considered to be heuristics. Arguably, a pruning technique is also a heuristic. That is exactly why I think that rather leaving  ``get_node_length_pairs`` and ``get_node_counter_pairs`` inside seperate modules, they should belong in a single file which consolidates those and similar functions. 

I propose they should exist in a module called ``prune.py`` or ``pruners.py`` as they are predefined special cases of pruning techniques. 

What is also shared between article.py and tabular.py is "optimizing" functions, aka ``argmax``. 

These should belong in either ``optimizers.py`` or ``maximizers.py``. 

Finally, and with less urgency, while I do think "metrics" is more terse than "quantifiers", what is lacking is the implication that those functions are active processes, meaning, they receive streams of nodes. "metrics" sounds static imo, but obviously these last few statements are subjective. 

I should note that the current goal I have for this project is to get rid of article.py and tabular.py as they are essentially what eatiht was. To be honest, if I wanted to keep things vanilla, I would have just implemented tabular.py into eatiht and I wouldn't bat an eye. 

But libextract is not eatiht, and its implementation should be more thought out (think of it as framework). All procedures should be clearly decoupled, so when article.py and tabular.py both execute **optimization** techniques, those techniques, or a generalized version, should exist in a single module, not in two separate modules.

**Comment by rodricios** [comment]
Just for funsies, here's what I'd like to do with a future version of libextract: after extracting a table from some html page, I'd like to be able to pipeline a function that will extract the longest piece of text in each row of that table. Or vice versa. Or I'd like to be able to extract numerical types in that table, etc.

**Comment by eugene-eeo** [comment]
I'm ok with this as long as the names are understandable and reasonable (not overly technical) given that most developers who are not familiar with ML would want to use the library as well, so the functions should be *intuitively* named.

**Comment by rodricios** [comment]
I see what you mean. And if you read the [README in autocomplete](https://github.com/rodricios/autocomplete), you'll see that I'm completely on the side of "less-technical". 

But I'm seeing myself joing the "darkside" (of the larger nomenclature war) simply because the alternatives like ``selectors.py`` or ``mappers.py`` have their own meanings, and I can imagine that using those or similar meaning words would confuse a user (as they will bring their own preconceived meanings along). 

*Selecting* reminds too much of the SQL/DB arena. *Mapping** sounds like I'm recording locations. If there are better alternatives to "prune" I'm all ears. 

Heuristics, I admit, is a horrible word to use, so let's not consider it. Optimizers/maximizers, I'm so-so about.

**Comment by eugene-eeo** [comment]
Yes, prejudices are a large part of naming things and how users perceive the names. And yes, you're right on the point when it comes to bad words to use- heurestics is a terrible word, I had to read the definition once or twice to understand what it means.

**Comment by eugene-eeo** [comment]
@rodricios about your point on separating the pruners into a separate module: although we should be as modular as possible, sometimes locality is a good thing. For example when developing we don't have to hop between too many files just to understand the code. Also, placing the related functions in one module (in this case, grouped by usage) would contribute to the "intuitiveness"- for example one should expect to fin a pruner that prunes for parent nodes and their text-lengths in the ``article`` module. Also, yielding the parent of the node is an implementation specific thing, I guess we can perhaps redefine the prunes decorator to be:

```python
def prunes(selector)
    def wrapper(fn):
        def mapper(etree):
            for node in etree:
                yield node, fn(node)
        return mapper
    return wrapper
```

And then define an article-specific histogram function:

```python
def node_parent_histogram(pairs):
    counter = Counter()
    for node, length in pairs:
        counter[node.getparent()] += length
    return counter
```

**Comment by rodricios** [comment]
@eugene-eeo what about naming the pruners: ``prune_articles`` and ``prune_tables``?

**Comment by rodricios** [comment]
>Also, yielding the parent of the node is an implementation specific thing, I guess we can perhaps redefine the prunes decorator to be:

>```python
def prunes(selector)
    def wrapper(fn):
        def mapper(etree):
            for node in etree:
                yield node, fn(node)
        return mapper
    return wrapper
```

>And then define an article-specific histogram function:

>```python
def node_parent_histogram(pairs):
    counter = Counter()
    for node, length in pairs:
        counter[node.getparent()] += length
    return counter
```

The issue with the above is that you don't leave the user that much control with returning the traversed nodes. 

So in the case that our user wants to create a custom ``basketing`` method (I'm using this term instead of ``pruning``), they're limitted to only creating a custom metric, when in fact, they should be able to do both: decide on not only the metric, but also the node they want to associate with that metric.

**Comment by eugene-eeo** [comment]
I don't think this deserves a separate issue, but I've recently took a look at other pipeline-libraries. I've noticed that most libraries use a class-based approach, for example:

```python
class GetNodeChildren(Pipe):
    def proc(self, node):
        return list(node)
```

Which is arguably more extensible because one can override the ``proc`` method to preprocess / post-process the data using ``super`` "hackery". And tinkerpop's (a collection of libraries to make creating graph databases easier) pipes library also has a [FilterPipe](https://github.com/tinkerpop/pipes/wiki/Filter-Pipes), something which could be implemented in our pipeline style by using:

```python
def filter_using(function):
    @wraps(function)
    def func(data):
        for item in data:
            if function(item):
                yield item
    return func
```

IMHO functions look better when declaring the stages of the pipeline, but classes give a more "solid" feel and are (arguably) more configurable, unless we manage to come up with something that is equally expressive.

**Comment by rodricios** [comment]
I like your ``filter_using`` decorator. Notice that we're creating more and more decorators that are acting like filters to node streams. We could try standardizing a set of decorating tools

**Comment by rodricios** [comment]
Here's a use case I see coming up for ``filter_using``
```python
from requests import get
from libextract import extract
from libextract.strategies import TABULAR
from libextract.coretools import node_processor
from libextract.formatters import table_json

@node_processor
def if_table(node):
    if node.tag == "table":
        return table_json(node)
    else:
        return node


height_data = get("http://en.wikipedia.org/wiki/Human_height")

strat = TABULAR + (if_table,)

tabs = list(extract(height_data.content, strategy=strat))

table = tabs[0]
table['Average male height'][:10]
# output
[u'174.0 cm (5 ft 8 1\u20442 in)',
 'N/A',
 u'173.48 cm (5 ft 8 1\u20442 in)',
 'N/A',
 u'175.6 cm (5 ft 9 in)',
 u'177.8 cm (5 ft 10 in)',
 u'179 cm (5 ft 10 1\u20442 in)',
 u'180 cm (5 ft 11 in)',
 u'178.80 cm (5 ft 10 1\u20442 in)',
 u'179.2 cm (5 ft 10 1\u20442 in)']
```

What if I wanted to have that data automatically formatted to decimals or floats? Or anything other than strings?

**Comment by eugene-eeo** [comment]
The conversion between string to floats should in my opinion be handled by the user. I think there are already libraries which exist to do this.

**Comment by rodricios** [comment]
Closing due to departure from the architecture present during the activity of this issue: #33
