### ISSUE TITLE
Move testing code into package

### ISSUE THREAD

**Issue by jjangsangy** [datalib/libextract#28]
So relative imports for packages works :+1: 

But now you want to move the test directory into your package so that `setuptools` also packages your testing code along with your package. After you do that and configure for imports, you want to include a `MANIFEST.in` file at the root which ensures all your asset files are also included when you install the package. 

Something along the lines of this should work

```manifest
include LICENSE
include .travis.yml
include requirements.txt
include libextract/tests/assets/full_of_foos.html

recursive-include libextract *.py
```

And then also adding this in your `setup.py` file.

```python
from setuptools import find_packages

setup(
...
    packages=find_packages(),
    tests_require=['pytest', 'nose'],
...
)
```

**Comment by eugene-eeo** [comment]
Could you verify that this works first?

**Comment by jjangsangy** [comment]
Sure, give me a sec

**Comment by jjangsangy** [comment]
So, change 

https://github.com/datalib/libextract/blob/master/MANIFEST.in#L4

to

```
include tests/assets/full_of_foos.html
```

Now `py.test` should succeed

**Comment by eugene-eeo** [comment]
I recursively included everything in tests/. Now it should (fingers crossed) work. Also everything in tests uses relative imports now.

**Comment by jjangsangy** [comment]
Ya, so I'm watching your travis build too.

But ya, let's see if this works

**Comment by jjangsangy** [comment]
So now we will need to fix this part.

```
python setup.py install &>/dev/null \
&& python -c 'import tests'  \
&& echo 'tests is a module' || echo ' tests isnt a module'

**Comment by eugene-eeo** [comment]
Ok so I got:

```
 ~/libextract(master) $ pip install .
Processing /Users/mango/libextract
Requirement already satisfied (use --upgrade to upgrade): chardet>=2.3.0 in /usr/local/lib/python3.4/site-packages (from libextract==0.0.0)
Requirement already satisfied (use --upgrade to upgrade): lxml>=3.4.0 in /usr/local/lib/python3.4/site-packages (from libextract==0.0.0)
Installing collected packages: libextract
  Running setup.py install for libextract
Successfully installed libextract-0.0.0
 ~/libextract(master) $ cd ..
 ~ $ python -c 'import tests' && echo 'tests is a module' || echo 'tests isnt a module'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named tests
tests isnt a module
```

**Comment by jjangsangy** [comment]
Cool, actually mine looks fine too. Looks like we might be solid.

Does `py.test` run ok?

**Comment by eugene-eeo** [comment]
Yup.

**Comment by jjangsangy** [comment]
Sweet! I'm not that familiar with `py.test` so didn't know if it would install or not install the testing directory.

**Comment by eugene-eeo** [comment]
Thanks so much for bearing with me and submitting this issue! Do let me know in the future about the packages you're maintaining that uses libextract.

**Comment by jjangsangy** [comment]
No probs, glad I could help!
