### ISSUE TITLE
Time for Pipeline class? 

### ISSUE THREAD

**Issue by rodricios** [datalib/libextract#29]
I'm enjoying the ``NodeProcessor`` class, but I think the usage practices are quite unnatractive:

```python
import re
from requests import get

from libextract import extract
from libextract.strategies import TABULAR
from libextract.formatters import table_json
from libextract.processor import NodeProcessor

# thoughts begin here
np = NodeProcessor()  # This is alright

# this is pretty, could be "prettier" if just @register('table')
@np.register('table')
def if_table(node):
    table = table_json(node)
    return table
...
strat = TABULAR + (np.process,) # This is starting to bug me :|
```

As for ideas of what do:

1. Some globally available Pipeline object (as in, initialized by top-level module ``__init__.py``
  * ``from libextract.processor import register, process``
  * even better: ``from libextract.processor import register`` and ``process`` is called in the background
2. Change ``strategy`` containers to ``list`` type 
  * no longer named with uppercase constant convention 
  * take advantage of ``append(fn)`` for adding methods to the end of the pipeline 

 ```python
from libextract.strategies import tabular
@register('tag')
def if_table(node):
...
tabular.append(if_table) 
strat = tabular
```

The above code block removes the need for the ``NodeProcessor.process`` method, which we then can move to ``register`` (I think...)

Thoughts? 
CC @datalib/contrib @datalib/admins

**Comment by eugene-eeo** [comment]
@rodricios but if we change it to list then future calls using ``tabular`` will now use the new strategy as lists can be modified in place. The better solution IMO is for the user to copy the strategy into their own list that they can pass around.

**Comment by rodricios** [comment]
Ok, what about just  we move the process method as an internal method within ``register``:

```python 
from libextract.processor import register
@register('table')
def if_table(node):
    table = table_json(node)
    return table

strat = TABULAR + (if_table,)
...
```

**Comment by eugene-eeo** [comment]
This approach uses globals which can be tricky to debug (and test).

**Comment by rodricios** [comment]
Hmm, I think I may be siding towards a Pipeline class where we can do the following instead: 

```python
from pipeline import Pipeline as pl

@pl.register
def if_table(node):
    ...
    return node or table
```
This likely requires a pretty hefty architectural redesign...  You up for it?

**Comment by eugene-eeo** [comment]
I'm not quite sure what the Pipeline class does :sweat:

**Comment by rodricios** [comment]
Not a problem :smile: 

So the goal of a ``Pipeline`` class is to consolidate a lot of the decorators that we define like so:
(Look for the node generator comment)
```python
# coretools.py
def prunes(selector):
    def decorator(fn):
        @wraps(fn)
        def mapper(etree): #### NODE GENERATOR (sorry for caps)
            for node in etree.xpath(selector): 
                yield fn(node)
        return mapper
    return decorator
...
# processor.py
class NodeProcessor:
    def process(self, nodes): #### NODE GENERATOR
        for node in nodes:
            if node.tag in self.mapping:
                yield self.mapping[node.tag](node)
                continue
            yield node
...
# formatters.py
def tabular_node_extractor(tag):
    def extract(node):
        for elem in node.iter(tag): #### NODE GENERATOR
            yield ' '.join(elem.text_content().split())
    return extract
```

I think we should create a Pipeline class that will receive parse html ``etree``

And then the ``Pipeline`` object will be responsible for accepting function hooks.

**Comment by rodricios** [comment]
One thing we should consider is this: 

We use ``xpath``, ``iter``, and sometimes ``iterchildren``, (look at the above first two referenced functions) in the first half of the strategy's pipeline execution.

Towards the later end of the pipeline, we use functions that accept iterables of nodes (like ``tabular.get_top_pairs``). 

To rephrase and roughly speaking, we use generators for the first half of the extraction algo, and in the later half, we tend to use methods that accept those generated iterables. But this statement may not be 100% correct...

**Comment by rodricios** [comment]
Closing this one
