### ISSUE TITLE
Confidence metric

### ISSUE THREAD

**Issue by eugene-eeo** [datalib/libextract#36]
The extremely naive way of implementing it would be:

``` python
def confidence(s, k):
    return (s[k] / s.mean()) - 1
```

Which has the nice property that it performs very well for datasets which are very imbalanced, i.e. the peak values are outliers, usually the case in a site's tabular content/text length. It also gives negative values for choices which are too small, which is IMHO a :+1:.

But the problem is that it returns too big a value for values that are too big, for example:

``` python
>>> from statscounter import StatsCounter
>>> from libextract.confidence import confidence_metric
>>> s = StatsCounter({'b':2, 'k': 3, 'd': 1, 'c': 20, 'f': 9})
>>> confidence_metric(s, 'c')
1.8571428571428572
```

I've experimented with other algorithms, for example:
- **(max - avg) / stdev** - performs well but has the same problem
- **max \* stddev / (size \* variance)** - gives nicer values and has the property that the confidence of the outliers do not exceed 1.

So far most of the algorithms do not have the property that **sum(P(k) for k in data) == 1.0**. This is a problem that I think can only be solved by probability distributions, which I do not know how to implement.

**Comment by eugene-eeo** [comment]
Seems like this problem can be solved using [cumulative distribution](https://en.wikipedia.org/wiki/Normal_distribution) variant of normal distribution (excuse the name of the function):

``` python
import math

def cumprob(x, median, stdev):
    erf = math.erf((x - median) / float(stdev * math.sqrt(2)))
    return 0.5 * (1 + erf)


def confidence(counter, key):
    return cummprob(
        counter[key],
        counter.median(),
        counter.stdev(),
    )
```

This approach has the nice property that the higher scoring nodes have a higher score that is not greater than 1 (approaches 1 but doesn't touch it) which is good because it emphasises that the library selects the nodes which are _probably_ the right ones, but cannot **_guarantee_** that they are. From the shape of the graph it is also exponentially decreasing for lower scoring nodes, which is a :+1:.

**cc** @rodricios

**Comment by rodricios** [comment]
I don't mean to nitpick but can you describe what you mean by the confidence metric? 

If we can decide on a clear definition, it should be easier to come to an algorithm. 

Btw, I agree a lot with this thought you had: 

> So far most of the algorithms do not have the property that sum(P(k) for k in data) == 1.0. This is a problem that I think can only be solved by probability distributions, which I do not know how to implement.

**Comment by rodricios** [comment]
Here's how to turn a frequency distribution to a probability distribution:

``` python
def normalize_distribution(counter):
    """"
    Given a *counter* (frequency distribution,
    AKA collections.Counter), normalize the frequencies
    to produce a probability distribution. 
    """
    total = sum(counter.values())
    return StatsCounter({k:v/total for k, v in counter.items()})


s = StatsCounter({'b':2, 'k': 3, 'd': 1, 'c': 20, 'f': 9})

prob_dist = normalize_distribution(s)
```

``` python
>>> prob_dist
StatsCounter({
    'c': 0.5714285714285714, 
    'f': 0.2571428571428571, 
    'k': 0.08571428571428572,
    'b': 0.05714285714285714, 
    'd': 0.02857142857142857
})

```

Edit: The above satisfies this property you pointed out: 

> So far most of the algorithms do not have the property that sum(P(k) for k in data) == 1.0.

``` python
>>> sum(prob_dist.values())
1.0
```

**Comment by eugene-eeo** [comment]
Ah so that's a probability distribution! I always thought of it as a relative stats dictionary. I think a confidence metric should be how confident the library is that some node is the correct one. Ideally it should have `sum(f(k) for k in R) == 1.0` but that doesn't need to strictly be true.

It is similar to the fitness functions used to rank samples in genetic (?) programming I suppose. I think that your solution is more elegant and predictable so I'm going with that.

**Comment by rodricios** [comment]
Feel free to implement it into StatsCounter's library :smile: 

There's a few extra "big picture" goals I have in mind for that library. I'll try to find time to tell you about it this weekend. *When are you free to talk on skype? Or Slack? I've never used the latter, but I've heard good things about it.

**Comment by eugene-eeo** [comment]
Will do. I'm free on Skype next Monday/Tuesday.

**Comment by rodricios** [comment]
Sounds good. Thanks man :)
