### ISSUE TITLE
extract method missing?

### ISSUE THREAD

**Issue by keevee09** [datalib/libextract#37]
I've just today pip installed libextract but noticed that
`from libextract.api import extract`
doesn't work. Neither does
`from libextract import extract`
Looking in my _site-packages/libextract_ directory I see that the _extract_ method is missing from all the source files.

**Comment by rodricios** [comment]
Wow, I'm sorry for this, expect a fix asap.

**Comment by rodricios** [comment]
Ok, just uploaded the latest build! Thanks for letting us know.

**Comment by keevee09** [comment]
No problem, thanks for the fast fix!

**Comment by rodricios** [comment]
:smile:
