### ISSUE TITLE
Short drop-in replacement for libextract

### ISSUE THREAD

**Issue by andreis** [datalib/libextract#39]
Here's a small implementation of the libextract algorithm:

```
def libextract(root, n=0, xpath=None):
    """Returns nodes with the most children with identical tags"""
    nodes = root.xpath(xpath or '//body//*/..')
    d = {node: collections.Counter(
        [c.tag for c in node]).most_common(1)[0][1]
        for node in nodes}
    nodes.sort(key=lambda x: d[x], reverse=True)
    return nodes[:n] if n else nodes


def libextract_test(et):
    print('\n'.join([et.getpath(node) for node in libextract(et, 10)]))

```

(Disclaimer, I understand what the goals for `libextract` and `StatsCounter`  are, this is just for fun)

**Comment by eugene-eeo** [comment]
Just for micro optimisation: you should do:

``` python
collections.Counter(c.tag for c in node)
```

Instead of the list comprehension just to avoid allocating a whole new list that's going to be disposed of each time :sweat_smile: But otherwise, nicely summarised!
